### ISSUE TITLE
Building with CUDA 9, 10...

### ISSUE THREAD

**Issue by w3b-net-au** [sjf/cuda_demosaicing#1]
Hi there,

Does anyone know how to remove old CUDA code (like cuda utilities) that was removed in CUDA 5 and later CUDA SDKs?

As far as I can tell a hack or work-around might be removing the cuda utils code and creating a new header, just cuda_utils.h, to resolve unknown functions and types, and making everything expecting the utils include that.

Then converting raw image files to PPM somehow: how did you achieve this in testing?  I have tried raw2ppm but it throws an I/O error.  I have raw files extracted from a  Norpix seq file, and need to convert these to PPM to try some multi GPU demosaicing.

Trying to get this compiling and working using CUDA Toolkit 10.2.  I'm using Ubuntu 18.04 LTS and Win 10.  Thanks for any tips or ideas on getting this code running again!

**Comment by w3b-net-au** [comment]
I got it compiling and building, but hit a brick wall on converting my raw format to PPM for the demosaicing step. :(

**Comment by sjf** [comment]
I haven't compiled this code in 10 years, so yes, it will need some work to compile with the latest version of CUDA. 
I was using a modified version of dcraw to convert the raw images.
